[tool.black]
target-version = ["py311"]
line-length = 100

[tool.ruff]
target-version = "py311"
line-length = 100
select = ["E", "F", "B", "I"]
ignore = ["E501"]

[tool.ruff.isort]
known-first-party = ["app"]
combine-as-imports = true

[tool.pytest.ini_options]
addopts = "-q"
pythonpath = ["."]
asyncio_mode = "strict"
